app = "midway"

kill_signal = "SIGINT"
kill_timeout = 15
processes = []

[env]
  CONN_TIMEOUT_SEC = "5"
  NOPROXY_TIMEOUT_SEC = "20"
  MAX_INFLIGHT_DNS_QUERIES = 1024
  UPSTREAM_DOH = "https://dns.google/dns-query"
  PROXY_DISABLED = "true"
  # TLS_CERT_PATH = "./test/certs/server.crt"
  # TLS_KEY_PATH = "./test/certs/server.key"
  # TLS_CERTKEY = "key=b64(server.key)\ncrt=b64(server.crt)"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

# echo tcp/udp svc on 5xxx
[[services]]
  auto_stop_machines = true
  auto_start_machines = false
  internal_port = 5000
  protocol = "udp"

  [[services.ports]]
    port = "5000"

[[services]]
  auto_stop_machines = true
  auto_start_machines = false
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
    port = "5000"

[[services]]
  auto_stop_machines = true
  auto_start_machines = false
  internal_port = 5001
  protocol = "tcp"

  [[services.ports]]
    handlers = ["proxy_proto"]
    port = "5001"

# h1x on 80
[[services]]
  auto_stop_machines = true
  auto_start_machines = false
  internal_port = 80
  protocol = "tcp"

  [services.concurrency]
  hard_limit = 4096
  soft_limit = 2048
  type = "connections"

  [[services.tcp_checks]]
  grace_period = "5s"
  interval = "30s"
  restart_limit = 6
  timeout = "3s"

  [[services.ports]]
    handlers = ["proxy_proto"]
    port = "80"

# proxifier and doh svc on 80, 443
[[services]]
  auto_stop_machines = true
  auto_start_machines = false
  internal_port = 443
  protocol = "tcp"

  [services.concurrency]
  hard_limit = 4096
  soft_limit = 2048
  type = "connections"

  [[services.tcp_checks]]
  grace_period = "5s"
  interval = "30s"
  restart_limit = 6
  timeout = "3s"

  [[services.ports]]
    handlers = ["proxy_proto"]
    port = "443"

# dot svc on port 853
[[services]]
  auto_stop_machines = true
  auto_start_machines = false
  internal_port = 853
  protocol = "tcp"

  [services.concurrency]
  hard_limit = 512
  soft_limit = 256
  type = "connections"

  [[services.tcp_checks]]
  grace_period = "5s"
  interval = "30s"
  restart_limit = 6
  timeout = "3s"

  [[services.ports]]
    handlers = ["proxy_proto"]
    port = "853"

# doh with fly-terminated tls on 1443
# community.fly.io/t/4449
[[services]]
  auto_stop_machines = true
  auto_start_machines = false
  internal_port = 1443
  protocol = "tcp"

  [services.concurrency]
  hard_limit = 512
  soft_limit = 256
  type = "connections"

  [[services.tcp_checks]]
  grace_period = "5s"
  interval = "30s"
  restart_limit = 6
  timeout = "3s"

  [[services.ports]]
    handlers = ["tls", "proxy_proto"]
    tls_options = { alpn = ["h2", "http/1.1"] }
    port = "1443"

# dot with fly-terminated tls on port 1853
# community.fly.io/t/4495
[[services]]
  auto_stop_machines = true
  auto_start_machines = false
  internal_port = 1853
  protocol = "tcp"

  [services.concurrency]
  hard_limit = 512
  soft_limit = 256
  type = "connections"

  [[services.tcp_checks]]
  grace_period = "5s"
  interval = "30s"
  restart_limit = 6
  timeout = "3s"

  [[services.ports]]
    handlers = ["tls", "proxy_proto"]
    port = "1853"
