app = "withered-bird-2688"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  ECHO_PORT = 5000

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 5000
  protocol = "udp"

  [[services.ports]]
    port = "5000"

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
    port = "5000"

[[services]]
  internal_port = 5001
  protocol = "tcp"

  [[services.ports]]
    handlers = ["proxy_proto"]
    port = "5001"

[[services]]
  internal_port = 443
  protocol = "tcp"

  [services.concurrency]
  hard_limit = 4096
  soft_limit = 2048
  type = "connections"

  [[services.tcp_checks]]
  grace_period = "5s"
  interval = "30s"
  restart_limit = 6
  timeout = "3s"

  [[services.ports]]
    handlers = ["proxy_proto"]
    port = "443"


[[services]]
  internal_port = 80
  protocol = "tcp"

  [services.concurrency]
  hard_limit = 4096
  soft_limit = 2048
  type = "connections"

  [[services.tcp_checks]]
  grace_period = "5s"
  interval = "30s"
  restart_limit = 6
  timeout = "3s"

  [[services.ports]]
    handlers = ["proxy_proto"]
    port = "80"
