name: Fly Deploy
on: 
  push:
    branches:
       - "main"
  workflow_dispatch:
    inputs:
      git-ref:
        description: "Branch / ref / tag to build"
        required: false
        default: "main"  
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP: ${{ secrets.FLY_APP_NAME }}


  
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: 🚢 Ship
          uses: superfly/flyctl-actions@1.1
